/*
 * This file was automatically generated by EvoSuite
 * Wed Nov 28 00:34:42 GMT 2018
 */

package com.jakubsprega.untestable.code.g;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.jakubsprega.untestable.code.g.ConsolePrinter;
import com.jakubsprega.untestable.code.g.TextFormat;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class ConsolePrinter_ESTest extends ConsolePrinter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ConsolePrinter consolePrinter0 = new ConsolePrinter();
      TextFormat textFormat0 = TextFormat.NORMAL;
      String string0 = consolePrinter0.formatText("", textFormat0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ConsolePrinter consolePrinter0 = new ConsolePrinter();
      TextFormat textFormat0 = TextFormat.UPPERCASE;
      // Undeclared exception!
      try { 
        consolePrinter0.print((String) null, textFormat0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.jakubsprega.untestable.code.g.ConsolePrinter", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ConsolePrinter consolePrinter0 = new ConsolePrinter();
      TextFormat textFormat0 = TextFormat.LOWERCASE;
      // Undeclared exception!
      try { 
        consolePrinter0.formatText((String) null, textFormat0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.jakubsprega.untestable.code.g.ConsolePrinter", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ConsolePrinter consolePrinter0 = new ConsolePrinter();
      TextFormat textFormat0 = TextFormat.UPPERCASE;
      String string0 = consolePrinter0.formatText("H[07RxZ$vYTDnZKpH", textFormat0);
      assertEquals("H[07RXZ$VYTDNZKPH", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ConsolePrinter consolePrinter0 = new ConsolePrinter();
      TextFormat textFormat0 = TextFormat.NORMAL;
      String string0 = consolePrinter0.formatText((String) null, textFormat0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ConsolePrinter consolePrinter0 = new ConsolePrinter();
      TextFormat textFormat0 = TextFormat.NORMAL;
      consolePrinter0.print("aqx65FeQ", textFormat0);
  }
}
