/*
 * This file was automatically generated by EvoSuite
 * Wed Nov 28 00:31:40 GMT 2018
 */

package com.jakubsprega.untestable.code.c;

import org.junit.Test;
import static org.junit.Assert.*;
import com.jakubsprega.untestable.code.c.WindowsGsmModule;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class WindowsGsmModule_ESTest extends WindowsGsmModule_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WindowsGsmModule windowsGsmModule0 = new WindowsGsmModule();
      windowsGsmModule0.connect();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      WindowsGsmModule windowsGsmModule0 = new WindowsGsmModule();
      windowsGsmModule0.sendSMS("", "");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      WindowsGsmModule windowsGsmModule0 = new WindowsGsmModule();
      windowsGsmModule0.disconnect();
  }
}
