/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 27 23:55:28 GMT 2018
 */

package com.jakubsprega.untestable.code.h;

import org.junit.Test;
import static org.junit.Assert.*;
import com.jakubsprega.untestable.code.h.Body;
import com.jakubsprega.untestable.code.h.Car;
import com.jakubsprega.untestable.code.h.Chassis;
import com.jakubsprega.untestable.code.h.Cylinder;
import com.jakubsprega.untestable.code.h.Engine;
import com.jakubsprega.untestable.code.h.Silencer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Car_ESTest extends Car_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Cylinder cylinder0 = new Cylinder();
      Engine engine0 = new Engine(cylinder0);
      Silencer silencer0 = new Silencer();
      Chassis chassis0 = new Chassis(silencer0);
      Car car0 = new Car(engine0, (Body) null, chassis0);
      Engine engine1 = car0.getEngine();
      assertSame(engine1, engine0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Engine engine0 = new Engine((Cylinder) null);
      Body body0 = new Body();
      Car car0 = new Car(engine0, body0, (Chassis) null);
      Chassis chassis0 = car0.getChassis();
      assertNull(chassis0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Cylinder cylinder0 = new Cylinder();
      Engine engine0 = new Engine(cylinder0);
      Silencer silencer0 = new Silencer();
      Chassis chassis0 = new Chassis(silencer0);
      Car car0 = new Car(engine0, (Body) null, chassis0);
      Body body0 = car0.getBody();
      assertNull(body0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Body body0 = new Body();
      Silencer silencer0 = new Silencer();
      Chassis chassis0 = new Chassis(silencer0);
      Car car0 = new Car((Engine) null, body0, chassis0);
      Engine engine0 = car0.getEngine();
      assertNull(engine0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Body body0 = new Body();
      Silencer silencer0 = new Silencer();
      Chassis chassis0 = new Chassis(silencer0);
      Car car0 = new Car((Engine) null, body0, chassis0);
      Body body1 = car0.getBody();
      assertSame(body0, body1);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Body body0 = new Body();
      Silencer silencer0 = new Silencer();
      Chassis chassis0 = new Chassis(silencer0);
      Car car0 = new Car((Engine) null, body0, chassis0);
      Chassis chassis1 = car0.getChassis();
      assertSame(chassis0, chassis1);
  }
}
