/*
 * This file was automatically generated by EvoSuite
 * Wed Nov 28 00:33:19 GMT 2018
 */

package com.jakubsprega.untestable.code.h;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import com.jakubsprega.untestable.code.h.Chassis;
import com.jakubsprega.untestable.code.h.Silencer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true, separateClassLoader = true) 
public class Chassis_ESTest extends Chassis_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Silencer silencer0 = mock(Silencer.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(silencer0).toString();
      Chassis chassis0 = new Chassis(silencer0);
      Silencer silencer1 = chassis0.getSilencer();
      assertSame(silencer1, silencer0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Chassis chassis0 = new Chassis((Silencer) null);
      Silencer silencer0 = chassis0.getSilencer();
      assertNull(silencer0);
  }
}
