/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 27 23:59:54 GMT 2018
 */

package com.jakubsprega.untestable.code.b;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.jakubsprega.untestable.code.api.Carrier;
import com.jakubsprega.untestable.code.b.AppleGsmModule;
import com.jakubsprega.untestable.code.b.VirginMobile;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AppleGsmModule_ESTest extends AppleGsmModule_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AppleGsmModule appleGsmModule0 = new AppleGsmModule();
      appleGsmModule0.sendSMS("virgin-mobile", "{YU736W0'%");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AppleGsmModule appleGsmModule0 = new AppleGsmModule();
      VirginMobile virginMobile0 = new VirginMobile();
      appleGsmModule0.setCarrier(virginMobile0);
      appleGsmModule0.disconnect();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AppleGsmModule appleGsmModule0 = new AppleGsmModule();
      VirginMobile virginMobile0 = new VirginMobile();
      appleGsmModule0.setCarrier(virginMobile0);
      appleGsmModule0.connect();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AppleGsmModule appleGsmModule0 = new AppleGsmModule();
      VirginMobile virginMobile0 = new VirginMobile();
      appleGsmModule0.setCarrier(virginMobile0);
      Carrier carrier0 = appleGsmModule0.getCarrier();
      assertSame(carrier0, virginMobile0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      AppleGsmModule appleGsmModule0 = new AppleGsmModule();
      // Undeclared exception!
      try { 
        appleGsmModule0.connect();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.jakubsprega.untestable.code.b.AppleGsmModule", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      AppleGsmModule appleGsmModule0 = new AppleGsmModule();
      Carrier carrier0 = appleGsmModule0.getCarrier();
      assertNull(carrier0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      AppleGsmModule appleGsmModule0 = new AppleGsmModule();
      // Undeclared exception!
      try { 
        appleGsmModule0.disconnect();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.jakubsprega.untestable.code.b.AppleGsmModule", e);
      }
  }
}
