/*
 * This file was automatically generated by EvoSuite
 * Wed Nov 28 00:31:58 GMT 2018
 */

package com.jakubsprega.untestable.code.b;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.jakubsprega.untestable.code.a.SamsungGsmModule;
import com.jakubsprega.untestable.code.api.GsmModule;
import com.jakubsprega.untestable.code.api.SmsMessage;
import com.jakubsprega.untestable.code.b.IPhone;
import com.jakubsprega.untestable.code.c.WindowsGsmModule;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class IPhone_ESTest extends IPhone_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IPhone iPhone0 = new IPhone();
      WindowsGsmModule windowsGsmModule0 = new WindowsGsmModule();
      iPhone0.setGsmModule(windowsGsmModule0);
      SmsMessage smsMessage0 = new SmsMessage("", (String) null);
      iPhone0.sendSMS(smsMessage0);
      assertNull(smsMessage0.getReceiver());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      IPhone iPhone0 = new IPhone();
      SamsungGsmModule samsungGsmModule0 = new SamsungGsmModule();
      iPhone0.setGsmModule(samsungGsmModule0);
      GsmModule gsmModule0 = iPhone0.getGsmModule();
      assertSame(gsmModule0, samsungGsmModule0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      IPhone iPhone0 = new IPhone();
      SamsungGsmModule samsungGsmModule0 = new SamsungGsmModule();
      iPhone0.setGsmModule(samsungGsmModule0);
      SmsMessage smsMessage0 = new SmsMessage("", (String) null);
      // Undeclared exception!
      try { 
        iPhone0.sendSMS(smsMessage0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Could not connect to ...
         //
         verifyException("com.jakubsprega.untestable.code.a.SamsungGsmModule", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      IPhone iPhone0 = new IPhone();
      GsmModule gsmModule0 = iPhone0.getGsmModule();
      assertNull(gsmModule0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      IPhone iPhone0 = new IPhone();
      SmsMessage smsMessage0 = new SmsMessage("", (String) null);
      // Undeclared exception!
      try { 
        iPhone0.sendSMS(smsMessage0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.jakubsprega.untestable.code.b.IPhone", e);
      }
  }
}
