/*
 * This file was automatically generated by EvoSuite
 * Wed Nov 28 00:32:23 GMT 2018
 */

package com.jakubsprega.untestable.code.b;

import org.junit.Test;
import static org.junit.Assert.*;
import com.jakubsprega.untestable.code.b.VirginMobile;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class VirginMobile_ESTest extends VirginMobile_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      VirginMobile virginMobile0 = new VirginMobile();
      String string0 = virginMobile0.getName();
      assertEquals("virgin-mobile", string0);
  }
}
