/*
 * This file was automatically generated by EvoSuite
 * Wed Nov 28 00:34:15 GMT 2018
 */

package com.jakubsprega.untestable.code.a;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.jakubsprega.untestable.code.a.SamsungGalaxyS3;
import com.jakubsprega.untestable.code.api.SmsMessage;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class SamsungGalaxyS3_ESTest extends SamsungGalaxyS3_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SamsungGalaxyS3 samsungGalaxyS3_0 = new SamsungGalaxyS3();
      SmsMessage smsMessage0 = new SmsMessage("", "");
      // Undeclared exception!
      try { 
        samsungGalaxyS3_0.sendSMS(smsMessage0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Could not connect to ...
         //
         verifyException("com.jakubsprega.untestable.code.a.SamsungGsmModule", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SamsungGalaxyS3 samsungGalaxyS3_0 = new SamsungGalaxyS3();
      List<SmsMessage> list0 = samsungGalaxyS3_0.getSentMessages();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SamsungGalaxyS3 samsungGalaxyS3_0 = new SamsungGalaxyS3();
      // Undeclared exception!
      try { 
        samsungGalaxyS3_0.sendSMS((SmsMessage) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.jakubsprega.untestable.code.a.SamsungGalaxyS3", e);
      }
  }
}
