/*
 * This file was automatically generated by EvoSuite
 * Wed Nov 28 00:32:58 GMT 2018
 */

package com.jakubsprega.untestable.code.a;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.jakubsprega.untestable.code.a.SamsungGsmModule;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class SamsungGsmModule_ESTest extends SamsungGsmModule_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SamsungGsmModule samsungGsmModule0 = new SamsungGsmModule();
      // Undeclared exception!
      try { 
        samsungGsmModule0.connect();
      } catch(IllegalStateException e) {
         //
         // Could not connect to ...
         //
         verifyException("com.jakubsprega.untestable.code.a.SamsungGsmModule", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SamsungGsmModule samsungGsmModule0 = new SamsungGsmModule();
      samsungGsmModule0.disconnect();
  }

  @Test
  public void test2()  throws Throwable  {
      SamsungGsmModule samsungGsmModule0 = new SamsungGsmModule();
      // Undeclared exception!
      try { 
        samsungGsmModule0.sendSMS("s,d0ErJ<w", "");
      } catch(IllegalStateException e) {
         //
         // Could not connect to ...
         //
         verifyException("com.jakubsprega.untestable.code.a.SamsungGsmModule", e);
      }
  }
}
