/*
 * This file was automatically generated by EvoSuite
 * Wed Nov 28 00:32:56 GMT 2018
 */

package com.jakubsprega.untestable.code.d;

import org.junit.Test;
import static org.junit.Assert.*;
import com.jakubsprega.untestable.code.d.IncomingCall;
import com.jakubsprega.untestable.code.d.OutgoingCall;
import java.util.Date;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.util.MockDate;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class Call_ESTest extends Call_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MockDate mockDate0 = new MockDate(0L);
      OutgoingCall outgoingCall0 = new OutgoingCall(0L, mockDate0);
      long long0 = outgoingCall0.getNumber();
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MockDate mockDate0 = new MockDate();
      IncomingCall incomingCall0 = new IncomingCall((-410L), mockDate0);
      long long0 = incomingCall0.getNumber();
      assertEquals((-410L), long0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MockDate mockDate0 = new MockDate();
      OutgoingCall outgoingCall0 = new OutgoingCall(145L, mockDate0);
      Date date0 = outgoingCall0.getDate();
      assertNotNull(date0);
      assertEquals(145L, outgoingCall0.number);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      OutgoingCall outgoingCall0 = new OutgoingCall(2595L, (Date) null);
      long long0 = outgoingCall0.getNumber();
      assertEquals(2595L, long0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      OutgoingCall outgoingCall0 = new OutgoingCall(2595L, (Date) null);
      outgoingCall0.getDate();
      assertEquals(2595L, outgoingCall0.number);
  }
}
