/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 27 23:58:42 GMT 2018
 */

package com.jakubsprega.untestable.code.api;

import org.junit.Test;
import static org.junit.Assert.*;
import com.jakubsprega.untestable.code.api.SmsMessage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SmsMessage_ESTest extends SmsMessage_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SmsMessage smsMessage0 = new SmsMessage("com.jakubsprega.untestable.code.api.SmsMessage", (String) null);
      String string0 = smsMessage0.getReceiver();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SmsMessage smsMessage0 = new SmsMessage("HQ:+T", "");
      String string0 = smsMessage0.getReceiver();
      assertEquals("HQ:+T", smsMessage0.getContent());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SmsMessage smsMessage0 = new SmsMessage((String) null, (String) null);
      String string0 = smsMessage0.getContent();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SmsMessage smsMessage0 = new SmsMessage("2.,=e+sZ", "Cr;m;TM1.P+p),74mB");
      String string0 = smsMessage0.getContent();
      assertEquals("Cr;m;TM1.P+p),74mB", smsMessage0.getReceiver());
      assertEquals("2.,=e+sZ", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SmsMessage smsMessage0 = new SmsMessage("", "CXq");
      String string0 = smsMessage0.getReceiver();
      assertEquals("", smsMessage0.getContent());
      assertEquals("CXq", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SmsMessage smsMessage0 = new SmsMessage("", "CXq");
      String string0 = smsMessage0.getContent();
      assertEquals("CXq", smsMessage0.getReceiver());
      assertEquals("", string0);
  }
}
