/*
 * This file was automatically generated by EvoSuite
 * Wed Nov 28 00:32:50 GMT 2018
 */

package com.jakubsprega.untestable.code.api;

import org.junit.Test;
import static org.junit.Assert.*;
import com.jakubsprega.untestable.code.api.SmsMessage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class SmsMessage_ESTest extends SmsMessage_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SmsMessage smsMessage0 = new SmsMessage((String) null, (String) null);
      String string0 = smsMessage0.getReceiver();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SmsMessage smsMessage0 = new SmsMessage("com.jakubsprega.untestable.code.api.SmsMessage", "com.jakubsprega.untestable.code.api.SmsMessage");
      String string0 = smsMessage0.getReceiver();
      assertEquals("com.jakubsprega.untestable.code.api.SmsMessage", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SmsMessage smsMessage0 = new SmsMessage((String) null, (String) null);
      String string0 = smsMessage0.getContent();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SmsMessage smsMessage0 = new SmsMessage("-@)$L{@k_YSEw?H", "");
      String string0 = smsMessage0.getContent();
      assertEquals("", smsMessage0.getReceiver());
      assertEquals("-@)$L{@k_YSEw?H", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SmsMessage smsMessage0 = new SmsMessage("", "");
      String string0 = smsMessage0.getReceiver();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SmsMessage smsMessage0 = new SmsMessage("", "");
      String string0 = smsMessage0.getContent();
      assertEquals("", string0);
  }
}
